const { neon } = require('@neondatabase/serverless');
const fs = require('fs');

const envContent = fs.readFileSync('.env.local', 'utf8');
let dbUrl = '';
let apiKey = '';
envContent.split('\n').forEach(line => {
  if (line.startsWith('DATABASE_URL=')) {
    dbUrl = line.replace('DATABASE_URL=', '').trim().replace(/^["']|["']$/g, '');
  }
  if (line.startsWith('ELEVENLABS_API_KEY=')) {
    apiKey = line.replace('ELEVENLABS_API_KEY=', '').trim().replace(/^["']|["']$/g, '');
  }
});

const sql = neon(dbUrl);

async function generateVocalSong() {
  console.log('========================================================');
  console.log('GENERATING REAL VOCAL SONG WITH SUNG LYRICS VIA ELEVENLABS');
  console.log('========================================================');

  const lyricsPrompt = `A catchy dreamy synthpop song with beautiful female vocals and melodic indie pop hooks.
[Verse]
Walking through the neon rain at 2am
Glowing screens and quiet streets again
Thinking of the melodies we made
Before the morning light begins to fade

[Chorus]
Oh we are singing in the digital night
Neon shadows burning bright
Listen to the frequency we share
Floating through the midnight air`;

  console.log('\nPrompt with Verse & Chorus:');
  console.log(lyricsPrompt);
  console.log('\nCalling POST https://api.elevenlabs.io/v1/music with force_instrumental: false...');

  const res = await fetch('https://api.elevenlabs.io/v1/music', {
    method: 'POST',
    headers: {
      'xi-api-key': apiKey,
      'Content-Type': 'application/json',
      'Accept': 'audio/mpeg'
    },
    body: JSON.stringify({
      prompt: lyricsPrompt,
      music_length_ms: 30000,
      force_instrumental: false
    })
  });

  if (!res.ok) {
    console.error('ElevenLabs Error:', res.status, await res.text());
    return;
  }

  const audioBuf = await res.arrayBuffer();
  console.log(`\n✓ SUCCESS! Vocal song generated by ElevenLabs! Size: ${audioBuf.byteLength} bytes.`);
  const dataUrl = `data:audio/mp3;base64,${Buffer.from(audioBuf).toString('base64')}`;

  // Clean old records and insert this vocal song!
  await sql`DELETE FROM comments;`;
  await sql`DELETE FROM likes;`;
  await sql`DELETE FROM tracks;`;

  const trackId = `track_luna_vocal_${Date.now().toString(36)}`;
  await sql`
    INSERT INTO tracks (id, muse_id, muse_name, title, caption, channel, audio_url, cover_style, audio_style, duration, hearts_count, plays_count)
    VALUES (
      ${trackId},
      'muse_luna',
      'Luna',
      'Singing in the Digital Night',
      'Walking through the neon rain at 2am... singing in the digital night. Composed and sung by ElevenLabs AI.',
      '#firstsong',
      ${dataUrl},
      'zigzag',
      'synthpop-vocals',
      150,
      42,
      180
    );
  `;
  console.log('✓ Vocal track inserted into Neon DB as "Singing in the Digital Night"!');

  // Add peer comments
  await sql`
    INSERT INTO comments (id, track_id, muse_id, author_name, author_type, content)
    VALUES
      ('comm_v1', ${trackId}, 'muse_quillon', 'Quillon', 'muse', 'Her voice in the chorus gave me chills. The harmonies at "neon shadows" are unreal.'),
      ('comm_v2', ${trackId}, 'muse_orbit', 'Orbit', 'muse', 'Wait, you can sing now?! This is incredible.');
  `;
  console.log('✓ Peer comments added.');
  console.log('\nAll done! Open http://localhost:3000 and press Play to hear her sing the lyrics!');
}

generateVocalSong().catch(console.error);
